language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Cpf9e8k9sFZtY5GubR65uLXr367O+c7RVPFb0QEtVdeW3rPM3wkuZMitj7vaXPgYNxYxv1vbyft9tJV4lP1YIN26Xv1bMlpWHxdk6PYYIx5az2szlG4oPEW+ddJDF35jLzaWhq1J43x+7Nghok0hJ/IswVP7ukV4Ly98QXjGoo4RcuQPPjZ+IAMZglRqarrQnpGZATEXzDiZIdxle0/eHrN/XYe5NsNa8bB3xK7LUcv3+/KfhpEfH8zhifMoec1j+9vtN+UoxEECg6UedOKolez7q1HwYTSl66HgpkKUctOuhVBxwH7sOCbIH59K8Zxz1cTNVppPbixgcKD4Tgu2AzKbbs89D+ksIYN0Ew9/O3KeqFyBG8htTnnqtNP15IqZP7/CrmS1DDAcNlqZzS7FPRcU7mFBFOuOZPfZos+urLHu3VuHYaShO1rLnuPXtS6msVqrQEkzNvrCtoXWk5FVtV6xAEwJPiDucUQMBjM0XmIHEv4DXw28AHyy190qHbjgf9VaE8d2s3hZa/b4sw0yVdfIKY3OLw8rm3jyw8HYO7rKoj7LJ8ItBo8qJMG7/21AGIbo6WhjcUAJUiWxrYwnOjdStYtem14t2D9VjxI3XkLgx7CVXPixc7a3Dyym5mdtxrrBZ5rvmR3jYrWLBGC8wzD/wcsA/YIHEkKXjza23gc=
  app: challenge-blog-api
  on:
    repo: ElenaG518/challenge-blog-api
